// This file is intended to be generated by Supabase CLI
// npx supabase gen types typescript --project-id <your-project-id> > types_db.ts
// For now we export a dummy type

export type Database = any;
